# Generated by Django 2.2.3 on 2019-07-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='Digite seu nome')),
                ('ultimo_nome', models.CharField(max_length=25, verbose_name='Digite seu ultimo nome')),
                ('endereco', models.CharField(max_length=50, verbose_name='Digite seu endereço')),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=50, verbose_name='Digite seu numero de telefone')),
            ],
            options={
                'verbose_name': 'nome',
                'verbose_name_plural': 'nomes',
                'ordering': ['nome'],
            },
        ),
    ]
